### ISSUE TITLE
explicit classes export 

### ISSUE THREAD

**Issue by rijnhard** [fasttime/Polytype#1]
Hi

In general manipulating global isn't a good idea (in some cases it does have value, so won't argue that) and it would be safer if we can just

```js
// explicit usage
import { classes } from 'polytype';

// global usage
import defineGlobally from 'polytype';
defineGlobally();
// or 
import 'polytype/global';
```

**Comment by fasttime** [comment]
Hi @rijnhard and thank you for your ideas. I was actually thinking to "refactor" Polytype into 3 version: a Vanilla JS version (with global definitions - this is the current state), a CommonJS version and an ES module version. The latter ones could be `import`ed in Node.js or Webpack in the way you show.

Note that `classes` is not the only global created by Polytype. There is also [`Object.getPrototypeListOf`](https://github.com/fasttime/Polytype/blob/0.0.1/lib/polytype.d.ts#L134) (it is not mentioned in the readme yet because it's still experimental). I'm still evaluating other options but the best I could find so far is exporting it as a regular function so you could do

```js
import { classes, getPrototypeListOf } from 'polytype';
const prototypes = getPrototypeListOf(obj);
```
instead of referencing the `Object` global.

I hadn't thought of a `defineGlobally` function but that would only work in an environment that supports some kind of modules, so it wouldn't be very useful in a plain vanilla environment, where the whole point of (ab)using global definitions is that you don't have modules. Granted, this is getting less of a problem since all newer browsers come with native ES module support.

**Comment by rijnhard** [comment]
I'd recommend using rollup. it makes it pretty easy to build for all 3 from agnostic code
