### ISSUE TITLE
Issue with Angular 8 in prod mode

### ISSUE THREAD

**Issue by josevargasgalan** [fasttime/Polytype#5]
When we launch the following command:
`ng serve --prod --source-map`

We get the following error:

>  ERROR in main.d558a3403cc855f52798.js from Terser
Unexpected token: punc ()) [./node_modules/polytype/lib/polytype.mjs:117,0][main.d558a3403cc855f52798.js:52044,4]

**Comment by fasttime** [comment]
This probably happens because Angular is running [terser](https://github.com/terser/terser) with option `ecma` set to 6 or 7 instead of 8 (the default).
Although the error above can be worked around, I think it would be a good idea nonetheless to upgrade your project to ECMAScript 2017 aka. ES8 syntax. This would give you access to newer JavaScript features without impacting the compatibility of your application – because Polytype only runs in new browsers anyway.

So to fix your specific issue I would suggest you go through the following steps (in order):

* In your Angular configuration, check what build tool or plugin is running terser, and configure it to pass the option `ecma: 8` (or `--ecma 8` from the command line). This should fix the error and may also improve the performace/size of your production code.
* If you run into troubles changing the terser options you could try to install version [0.6.0-beta.1](https://github.com/fasttime/Polytype/releases/tag/0.6.0-beta.1) where I made small changes to enforce ES6 syntax compatibility.
* If the above suggestions don't work, please post the output of `ng --version` and your Angular/Webpack configs, so I can reproduce the issue.

**Comment by josevargasgalan** [comment]
Thanks! updating angular solves the issue

**Comment by fasttime** [comment]
Fine! Leaving this open as a reminder to elaborate the documentation.
