### ISSUE TITLE
Issue with ngOnDestry method when use polytype

### ISSUE THREAD

**Issue by franciscojoseramosespinar** [fasttime/Polytype#6]
I have a component that navigate to other page when finish the method _ngOnInit_:
```
import { Component, OnInit } from '@angular/core';
import { ClassA } from './classA';
import { ClassB } from './classB';
import { classes } from 'polytype';
import { ClassAService} from './classA.service';
import { ClassBService} from './classB.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent extends classes(ClassA, ClassB)  {

  constructor(
    classAService: ClassAService,
    classBService: ClassBService
) {
    super(['classAService'], ['classBService']);
  }

  ngOnInit(): void {
    // Do something and navigate to other page
  }
}
```

The issue come when both extended classes have _ngOnDestroy_ method, **only the first class execute _ngOnDestroy_** and should both classes execute It. I need to do the following to make it works correctly but I think It is not the best option:

```
 ngOnInit(): void {
    // Navigate to other page
   super.class(ClassB).ngOnDestroy();
  }
```

Thank you for your great work I look forward to your answer.

**Comment by fasttime** [comment]
In fact, Angular calls `ngOnDestroy` only once per object, regardless of class hierarchy.
Since your `AppComponent` extends two classes, both implementing `ngOnDestroy`, only the first implementation is being called.
This is a known caveat: there is no concise method to change this behavior.
If what you need is actually calling multiple base implementations in turn, I'd suggest writing your own `ngOnDestroy`.

```ts
  ngOnInit(): void {
    // Do something and navigate to other page
    // No need to call ngOnDestroy directly here!
  }
  
  ngOnDestroy(): void {
    super.class(ClassA).ngOnDestroy();
    super.class(ClassB).ngOnDestroy();
  }
```
You could also iterate over the direct base classes and call `ngOnDestroy` in a loop.

```ts
import { classes, getPrototypeListOf } from 'polytype';

  ...

  ngOnDestroy(): void {
    for (const baseClass of getPrototypeListOf(AppComponent)) {
      super.class(baseClass).ngOnDestroy();
    }
  }

  ...
```

Finally, you could create a custom type decorator to annotate your class instead of writing a new method.
This is especially useful if you have multiple places in code that rely on the same pattern.

```ts
import { OnDestroy } from '@angular/core';
import { getPrototypeListOf } from 'polytype';

export function DestroyBases<T extends { new(...args: any[]): { } }>(derivedClass: T) {
    const prototypeList = getPrototypeListOf(derivedClass.prototype);
    return class extends derivedClass implements OnDestroy {
        ngOnDestroy(): void {
            for (const prototype of prototypeList) {
                if ('ngOnDestroy' in prototype) {
                    prototype.ngOnDestroy.call(this);
                }
            }
        }
    };
}
```

Then just add the annotation `@DestroyBases` to `AppComponent`.

```ts
  @Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.sass']
  })
  @DestroyBases
  export class AppComponent extends classes(ClassA, ClassB)  {
```

Please, let me know if this does not solve your problem or if you need more help.

**Comment by franciscojoseramosespinar** [comment]
Decorator is the best idea and works correctly, thank you so much.
